# -*- coding: utf-8 -*-
"""ADIKARA 2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/faisalwp/adikara-2025.b992d58a-ecf9-4bbb-a9cf-af6a808424c8.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251212/auto/storage/goog4_request%26X-Goog-Date%3D20251212T075229Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D6510805a1ff8030a3313c59cbf9d42726a93c07d0abe545676b6b78091a0dd9bfbce9a8cb309a805803c78e12bd915b45ebe07e19a354db726364add8126a9407636c732fd4bc6b68477cb1e09eb92d8fa465fb66e468f6e74b10b0acdcd827b70ee62101490edad15c95b69cff4c2e11191e8c4437ae1a3a385b69ff359bc1d252f813dd3b9b598085ff865cb36e66c07d3a47c47c627a447faad33937893810d4dbc896b75087d93c0fc4459f4f3d94b796a604d8b532b12e7229ae375a73d17a4620f296e5c022cee4ffb429f140808758eab9dfd4946e090fd6ce41aa9cd8f883d0d5faf4e4d3a24581133bce95e1f52c2c7eb5998a60db3f15da25892c8
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

adikara_2025_indonesia_kredit_macet_path = kagglehub.competition_download('adikara-2025-indonesia-kredit-macet')

print('Data source import complete.')

import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, classification_report

# Mematikan warning agar output bersih
warnings.filterwarnings('ignore')

# ==============================================================================
# 1. LOAD DATASET
# ==============================================================================

# Path
path_train = '/kaggle/input/adikara-2025-indonesia-kredit-macet/train.csv'
path_test = '/kaggle/input/adikara-2025-indonesia-kredit-macet/test.csv'
path_sample = '/kaggle/input/adikara-2025-indonesia-kredit-macet/sample_submissions.csv'

print(f"Membaca data train dari: {path_train}")

try:
    train = pd.read_csv(path_train)
    test = pd.read_csv(path_test)
    submission = pd.read_csv(path_sample)
    print("Berhasil memuat semua dataset!")
except FileNotFoundError as e:
    print(f"\nERROR: File tidak ditemukan. Pesan error: {e}")
    print("Pastikan dataset 'adikara-2025-indonesia-kredit-macet' sudah ditambahkan ke notebook ini (tombol + Add Data di kanan atas).")
    raise # Hentikan proses jika file tidak ada

# ==============================================================================
# 2. FEATURE ENGINEERING & CLEANING
# ==============================================================================

# Menggabungkan data
train['is_train'] = 1
test['is_train'] = 0
test['status_gagal_bayar'] = np.nan
df = pd.concat([train, test], ignore_index=True)

# A. Ekstrak Informasi Tanggal
df['tanggal_pencairan'] = pd.to_datetime(df['tanggal_pencairan'])
df['tahun'] = df['tanggal_pencairan'].dt.year
df['bulan'] = df['tanggal_pencairan'].dt.month
# Hapus kolom datetime asli
df = df.drop(columns=['tanggal_pencairan'])

# B. Fitur Finansial Baru
df['bunga_nominal'] = df['total_pengembalian'] - df['jumlah_pinjaman']
df['bunga_persen'] = df['bunga_nominal'] / df['jumlah_pinjaman']
df['cicilan_harian'] = df['total_pengembalian'] / df['durasi_hari']
df['ratio_lender'] = df['porsi_pengembalian_lender'] / df['total_pengembalian']

# --- [PEMBERSIHAN DATA] ---
# Mencegah error "Input X contains NaN" atau Infinity
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)
print("Data berhasil dibersihkan dari nilai NaN dan Infinity.")

# C. Encoding Kategorikal
cat_cols = ['provinsi', 'jenis_pinjaman', 'status_peminjam',
            'sektor_usaha', 'pendidikan', 'jenis_jaminan']

le = LabelEncoder()
for col in cat_cols:
    df[col] = df[col].astype(str)
    df[col] = le.fit_transform(df[col])

# ==============================================================================
# 3. MODELING (RANDOM FOREST)
# ==============================================================================

# data Train dan Test
df_train_final = df[df['is_train'] == 1].drop(columns=['is_train'])
df_test_final = df[df['is_train'] == 0].drop(columns=['is_train', 'status_gagal_bayar'])

target = 'status_gagal_bayar'
fitur = [c for c in df_train_final.columns if c not in [target, 'id_transaksi']]

X = df_train_final[fitur]
y = df_train_final[target].astype(int)
X_test_pred = df_test_final[fitur]

# Split Validasi
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("\nSedang melatih model Random Forest...")
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=15,
    class_weight='balanced', # Menyeimbangkan kelas lancar vs macet
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

# Evaluasi Awal
y_pred_val = model.predict(X_val)
score = f1_score(y_val, y_pred_val, average='macro')
print(f"\nVALIDATION MACRO F1-SCORE: {score:.5f}")

# ==============================================================================
# 4. SUBMISSION
# ==============================================================================

# Train full data
model.fit(X, y)
# Prediksi data test
y_submission = model.predict(X_test_pred)

# Simpan
submission['status_gagal_bayar'] = y_submission
submission.to_csv('submission.csv', index=False)

